#!/bin/bash

# Copyright 2025 Oleh Nykyforchyn, Ivano-Frankivsk, Ukraine

if egrep '^[^[:blank:]]*blacklist[^[:blank:]][^[:blank:]]*nouveau[^[:blank:]]*$' \
        /etc/modprobe.d/* > /dev/null ; then
    echo "It seems that nouveau is blacklisted somewhere in /etc/modprobe.d/, remove this!"
fi

if [ -z "$KERNELVER" ] ; then
  KERNELVER=`uname -r`
fi

if [ ! -r /boot/vmlinuz-$KERNELVER ] ; then
    echo "There is no vmlinuz-$KERNELVER kernel, cannot proceed!"
    exit 1
fi

if [ ! -r /lib/modules/$KERNELVER/kernel/drivers/video/nvidia.ko -o \
     ! -r /lib/modules/$KERNELVER/kernel/drivers/video/nvidia-uvm.ko ] ; then
    echo "NVidia modules missing for linux-$KERNELVER kernel, cannot proceed!"
    exit 1
fi

ROOT=`cat /etc/mtab | egrep '^[^[:blank:]]* / '`
if [ -z "$ROOT" ] ; then
    echo "There is no line for root fs in /etc/mtab, cannot proceed!"
    exit 1
else
    ROOT=`echo $ROOT | cut -f 1 -d ' '`
(
cat <<EOF
# Linux bootable partition config begins
image = /boot/vmlinuz-KERNELVER
  root = ROOT
  label = Linux-KERNELVER+
  read-only  # Partitions should be mounted read-only for checking
  initrd = /boot/initrd-KERNELVER.img
  append = " module_blacklist=nouveau"
# Linux bootable partition config ends
# Linux bootable partition config begins
image = /boot/vmlinuz-KERNELVER
  root = ROOT
  label = Linux-KERNELVER-
  read-only  # Partitions should be mounted read-only for checking
  initrd = /boot/initrd-KERNELVER.img
  append = " module_blacklist=nvidia,nvidia_uvm"
# Linux bootable partition config ends
EOF
) | sed "s|KERNELVER|$KERNELVER|" \
  | sed "s|ROOT|$ROOT|" > /etc/lilo.conf.nvidia-$KERNELVER
fi

